version: '3'
services:

  LDAP:
    image: testapp/webpdf-wsclient-ldap:latest
    build:
      context: ./ldap
      dockerfile: Dockerfile
    environment:
      - PORT=10389
    ports:
      - "10389:10389"
    tty:
      true
    stdin_open:
      true

  webPDF:
    image: testapp/webpdf-wsclient-server:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      LDAP:
        condition: service_started
    ports:
      - "8080:8080"
      - "8443:8443"
      - "8888:8888"
    tty:
      true
    stdin_open:
      true
