version: '3'
services:

  LDAP:
    image: testapp/webpdf-wsclient-ldap:latest
    build:
      context: ./ldap
      dockerfile: Dockerfile
    environment:
      - PORT=10389
    ports:
      - "10389:10389"
    tty:
      true
    stdin_open:
      true

  Proxy:
    image: mitmproxy/mitmproxy
    ports:
      - "8888:8888"
    entrypoint: '/bin/sh -c "stty rows 24 cols 80 && mitmdump -p8888 --ssl-insecure"'
    tty:
      true
    stdin_open:
      true

  webPDF:
    image: testapp/webpdf-wsclient-server:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      LDAP:
        condition: service_started
    ports:
      - "8080:8080"
      - "8443:8443"
    tty:
      true
    stdin_open:
      true
